# Cron helper: https://crontab.guru

Cars::RobotBuilder::BuildJob:
  cron: '* * * * *' # every 1m
  queue: schedule_jobs

Cars::RobotBuilder::CleanCars:
    cron: '10 4 * * *' # every 1d at 04:10
    queue: schedule_jobs
