# Cron helper: https://crontab.guru

Cars::RobotBuilder::BuildJob:
  cron: '* * * * *' # every 1m
  queue: schedule_jobs

Cars::RobotBuilder::CleanCarsJob:
    cron: '10 1 * * *' # every 1d at 01:10
    queue: schedule_jobs

Cars::GuardRobot::CarsTransferJob:
  cron: '*/30 * * * *' # every 30m
  queue: schedule_jobs

Cars::RobotBuyer::BuyJob:
  cron: '* * * * *' # every 1m
  queue: schedule_jobs
